# Generated by Django 3.0.6 on 2022-05-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backbone',
            fields=[
                ('backbone_id', models.AutoField(primary_key=True, serialize=False, verbose_name='干线ID')),
                ('level', models.CharField(max_length=40, verbose_name='方案层级')),
                ('avg_delay', models.FloatField(default=0, null=True, verbose_name='总体延误')),
                ('queue_length', models.FloatField(default=0, null=True, verbose_name='排队长度')),
                ('flow_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='周期内流量')),
                ('service_level', models.CharField(max_length=40, verbose_name='通行服务等级')),
                ('signal_rationality', models.FloatField(default=0, null=True, verbose_name='信号合理性')),
                ('paused_vehicle_num', models.FloatField(default=0, null=True, verbose_name='停驶车辆数')),
                ('avg_passed_vehicle_num', models.FloatField(default=0, null=True, verbose_name='平均通过车辆数')),
                ('greenrate', models.FloatField(default=0, null=True, verbose_name='绿灯利用率')),
            ],
            options={
                'db_table': 'backbone',
            },
        ),
        migrations.CreateModel(
            name='BackboneOptimized',
            fields=[
                ('backbone_id', models.AutoField(primary_key=True, serialize=False, verbose_name='优化后干线ID')),
                ('level', models.CharField(max_length=40, verbose_name='方案层级')),
                ('avg_delay', models.FloatField(default=0, null=True, verbose_name='总体延误')),
                ('queue_length', models.FloatField(default=0, null=True, verbose_name='排队长度')),
                ('flow_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='周期内流量')),
                ('service_level', models.CharField(max_length=40, verbose_name='通行服务等级')),
                ('signal_rationality', models.FloatField(default=0, null=True, verbose_name='信号合理性')),
                ('paused_vehicle_num', models.FloatField(default=0, null=True, verbose_name='停驶车辆数')),
                ('avg_passed_vehicle_num', models.FloatField(default=0, null=True, verbose_name='平均通过车辆数')),
                ('greenrate', models.FloatField(default=0, null=True, verbose_name='绿灯利用率')),
            ],
            options={
                'db_table': 'backboneoptimized',
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('road_id', models.AutoField(primary_key=True, serialize=False, verbose_name='路口ID')),
                ('level', models.CharField(max_length=40, verbose_name='方案层级')),
                ('avg_delay', models.FloatField(default=0, null=True, verbose_name='总体延误')),
                ('queue_length', models.FloatField(default=0, null=True, verbose_name='排队长度')),
                ('flow_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='周期内流量')),
                ('service_level', models.CharField(max_length=40, verbose_name='通行服务等级')),
                ('signal_rationality', models.FloatField(default=0, null=True, verbose_name='信号合理性')),
                ('paused_vehicle_num', models.FloatField(default=0, null=True, verbose_name='停驶车辆数')),
                ('avg_passed_vehicle_num', models.FloatField(default=0, null=True, verbose_name='平均通过车辆数')),
                ('greenrate', models.FloatField(default=0, null=True, verbose_name='绿灯利用率')),
            ],
            options={
                'db_table': 'effect',
            },
        ),
        migrations.CreateModel(
            name='EffectOptimized',
            fields=[
                ('road_id', models.AutoField(primary_key=True, serialize=False, verbose_name='优化后路口ID')),
                ('level', models.CharField(max_length=40, verbose_name='方案层级')),
                ('avg_delay', models.FloatField(default=0, null=True, verbose_name='总体延误')),
                ('queue_length', models.FloatField(default=0, null=True, verbose_name='排队长度')),
                ('flow_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='周期内流量')),
                ('service_level', models.CharField(max_length=40, verbose_name='通行服务等级')),
                ('signal_rationality', models.FloatField(default=0, null=True, verbose_name='信号合理性')),
                ('paused_vehicle_num', models.FloatField(default=0, null=True, verbose_name='停驶车辆数')),
                ('avg_passed_vehicle_num', models.FloatField(default=0, null=True, verbose_name='平均通过车辆数')),
                ('greenrate', models.FloatField(default=0, null=True, verbose_name='绿灯利用率')),
            ],
            options={
                'db_table': 'effectoptimized',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False, verbose_name='总体ID')),
                ('level', models.CharField(max_length=40, verbose_name='方案层级')),
                ('avg_delay', models.FloatField(default=0, null=True, verbose_name='总体延误')),
                ('queue_length', models.FloatField(default=0, null=True, verbose_name='排队长度')),
                ('flow_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='周期内流量')),
                ('service_level', models.CharField(max_length=40, verbose_name='通行服务等级')),
                ('signal_rationality', models.FloatField(default=0, null=True, verbose_name='信号合理性')),
                ('paused_vehicle_num', models.FloatField(default=0, null=True, verbose_name='停驶车辆数')),
                ('avg_passed_vehicle_num', models.FloatField(default=0, null=True, verbose_name='平均通过车辆数')),
                ('greenrate', models.FloatField(default=0, null=True, verbose_name='绿灯利用率')),
            ],
            options={
                'db_table': 'summary',
            },
        ),
        migrations.CreateModel(
            name='SummaryOptimized',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False, verbose_name='优化后总体ID')),
                ('level', models.CharField(max_length=40, verbose_name='方案层级')),
                ('avg_delay', models.FloatField(default=0, null=True, verbose_name='总体延误')),
                ('queue_length', models.FloatField(default=0, null=True, verbose_name='排队长度')),
                ('flow_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='周期内流量')),
                ('service_level', models.CharField(max_length=40, verbose_name='通行服务等级')),
                ('signal_rationality', models.FloatField(default=0, null=True, verbose_name='信号合理性')),
                ('paused_vehicle_num', models.FloatField(default=0, null=True, verbose_name='停驶车辆数')),
                ('avg_passed_vehicle_num', models.FloatField(default=0, null=True, verbose_name='平均通过车辆数')),
                ('greenrate', models.FloatField(default=0, null=True, verbose_name='绿灯利用率')),
            ],
            options={
                'db_table': 'summaryoptimized',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('configuration_id', models.AutoField(primary_key=True, serialize=False, verbose_name='相位ID')),
                ('level', models.CharField(max_length=40, verbose_name='方案层级')),
                ('period', models.SmallIntegerField(default=0, null=True, verbose_name='周期')),
                ('green_st', models.FloatField(default=0, null=True, verbose_name='开始时间')),
                ('green_end', models.FloatField(default=0, null=True, verbose_name='结束时间')),
                ('greenrate', models.FloatField(default=0, null=True, verbose_name='绿信比')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Effect')),
            ],
            options={
                'db_table': 'configuration',
            },
        ),
    ]
