# Generated by Django 3.0.6 on 2022-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backbone',
            name='flow_volume',
            field=models.FloatField(default=0, null=True, verbose_name='周期内流量'),
        ),
        migrations.AlterField(
            model_name='backboneoptimized',
            name='flow_volume',
            field=models.FloatField(default=0, null=True, verbose_name='周期内流量'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='flow_volume',
            field=models.FloatField(default=0, null=True, verbose_name='周期内流量'),
        ),
        migrations.AlterField(
            model_name='effectoptimized',
            name='flow_volume',
            field=models.FloatField(default=0, null=True, verbose_name='周期内流量'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='flow_volume',
            field=models.FloatField(default=0, null=True, verbose_name='周期内流量'),
        ),
        migrations.AlterField(
            model_name='summaryoptimized',
            name='flow_volume',
            field=models.FloatField(default=0, null=True, verbose_name='周期内流量'),
        ),
    ]
