# Generated by Django 3.0.6 on 2022-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220506_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='road_name',
            field=models.CharField(max_length=40, null=True, verbose_name='路口名称'),
        ),
        migrations.AddField(
            model_name='effectoptimized',
            name='road_name',
            field=models.CharField(max_length=40, null=True, verbose_name='优化后路口名称'),
        ),
    ]
