# Generated by Django 3.0.6 on 2022-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220506_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='jingdu',
            field=models.FloatField(default=0, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='effect',
            name='weidu',
            field=models.FloatField(default=0, null=True, verbose_name='纬度'),
        ),
    ]
